### ISSUE TITLE
[make] No instructions to clone git submodules prior to using make

### ISSUE THREAD

**Issue by chris-lansman** [jakcron/nstool#96]
Downloaded the latest source and attempted to compile on ubuntu 20.04, you receive this error
`CXX src/util.cpp
In file included from src/util.h:2,
                 from src/util.cpp:1:
src/types.h:2:10: fatal error: tc/types.h: No such file or directory
    2 | #include <tc/types.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [makefile:130: src/util.o] Error 1`

After spending an hour+ googling around this file as far as I can surmise no longer lives in the `tc` tool which is now part of the `iproute2` package. 

Please consider updating these dependencies or at least making a link or download available on where to get them from in order to compile the code. 

I attempted to run your pre-compiled and it died trying to find old versions of GLIBC. Consider recompiling with a new version of Linux or specifying what you are running.

**Comment by jakcron** [comment]
It's actually part of libtoolchain, I see it's missing from the build steps so i will just tell you here, and update it later.

The deps/ directory contains all the local dependencies required to build NSTool.
But they are **git submodules**, so when first cloning the source code you need to init the git submodules and clone them with these two commands:
```
git submodule init
git submodule update
```

**Comment by jakcron** [comment]
> I attempted to run your pre-compiled and it died trying to find old versions of GLIBC. Consider recompiling with a new version of Linux or specifying what you are running.

The pre-compiled binaries are built using Github Actions, Ubuntu builds specifically use `ubuntu-latest`, so there's not much chance of it being built with a "newer" version of linux.

**Comment by jakcron** [comment]
Instructions added to BUILDING.md in `development-tip` (https://github.com/jakcron/nstool/commit/0d248d1c8e6fb9fc3c23f7add7b0e570d294d6d7). This should be present in any release post 1.8.0

**Comment by jakcron** [comment]
Released in NSTool v1.8.1
